name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Stats + Languages
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/github-metrics.svg
          base: header, activity, community, repositories
          base_indepth: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_threshold: 1%
          config_timezone: Asia/Kuala_Lumpur
          config_display: large

      # Achievements
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/achievements.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_display: compact
          config_display: large

      # Contribution calendar
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: profile/isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          config_timezone: Asia/Kuala_Lumpur
